name: run tests and report results
on: [pull_request]
jobs:
    tests:
        runs-on: ubuntu-latest
        strategy:
            matrix:
                python: [3.6, 3.7, 3.8, 3.9]
        name: Python ${{ matrix.python }}
        steps:
            - name: Checkout branch
              uses: actions/checkout@v2

            - name: Setup pyton ${{ matrix.python }}
              uses: actions/setup-python@master
              with:
                python-version: ${{ matrix.python }}

            - name: Install poetry
              uses: dschep/install-poetry-action@v1.3
              with:
                version: 1.0.9
                create_virtualenvs: true

            - name: Install dependencies
              run: |
                source $HOME/.poetry/env
                poetry install

            - name: Run tests and generate coverage report
              run: |
                poetry run pytest tests/ --ignore=tests/datafiles --cov=./ --cov-report=xml

            - name: Upload coverage report to Codecov
              uses: codecov/codecov-action@v1
              with:
                token: ${{ secrets.CODECOV_TOKEN }}
                file: ./coverage.xml
                flags: unittests
                name: codecov-umbrella
                fail_ci_if_error: true